import type { DesktopUiLanguage } from "@c4ml/desktop-contract";

const englishMessages = {
  "menu.settings": "Settings…",
  "menu.file": "File",
  "menu.open": "Open…",
  "menu.openProject": "Open Project…",
  "menu.closeDocument": "Close File",
  "menu.closeProject": "Close Project",
  "menu.save": "Save",
  "menu.saveAll": "Save All",
  "menu.saveAs": "Save As…",
  "menu.exportPng": "Export PNG…",
  "menu.edit": "Edit",
  "menu.undo": "Undo",
  "menu.redo": "Redo",
  "menu.cut": "Cut",
  "menu.copy": "Copy",
  "menu.paste": "Paste",
  "menu.pasteMatch": "Paste and Match Style",
  "menu.delete": "Delete",
  "menu.selectAll": "Select All",
  "menu.view": "View",
  "menu.reload": "Reload",
  "menu.forceReload": "Force Reload",
  "menu.devTools": "Toggle Developer Tools",
  "menu.resetZoom": "Actual Size",
  "menu.zoomIn": "Zoom In",
  "menu.zoomOut": "Zoom Out",
  "menu.fullscreen": "Toggle Full Screen",
  "menu.previewFocus": "Full-size Diagram Workspace",
  "menu.previewWindow": "Open Diagram Window",
  "menu.window": "Window",
  "menu.minimize": "Minimize",
  "menu.zoom": "Zoom",
  "menu.front": "Bring All to Front",
  "menu.close": "Close Window",
  "menu.about": "About C4thedral",
  "menu.services": "Services",
  "menu.hide": "Hide C4thedral",
  "menu.hideOthers": "Hide Others",
  "menu.showAll": "Show All",
  "menu.quit": "Quit C4thedral",
  "dialog.exportPng": "Export PNG diagram",
  "dialog.exportSvg": "Export SVG diagram",
  "dialog.open": "Open C4ML source",
  "dialog.openProject": "Open C4ML project directory",
  "dialog.save": "Save C4ML source",
  "filter.png": "PNG image",
  "filter.svg": "SVG image",
  "filter.c4ml": "C4ML source",
  "filter.all": "All files",
  "error.svgTooLarge": "The SVG diagram is larger than the 16 MiB desktop limit.",
  "error.svgSave": "The SVG diagram could not be saved at the selected location.",
  "error.pngRender": "The current SVG diagram could not be rendered as PNG.",
  "error.pngSave": "The PNG diagram could not be saved at the selected location.",
  "error.sourceUnreadable": "The selected source is not a readable C4ML file below 8 MiB.",
  "error.projectUnreadable": "At least one project source exceeds the 8 MiB desktop limit.",
  "error.sourceTooLarge": "The C4ML source is larger than the 8 MiB desktop limit.",
  "error.sourceSave": "The C4ML source could not be saved at the selected location.",
  "error.ipc": "The desktop request was rejected by the application boundary.",
  "error.sourceRead": "The selected C4ML source could not be read.",
  "close.title": "Unsaved C4ML source",
  "close.message": "Discard changes to {name}?",
  "close.detail": "The source contains changes that have not been saved.",
  "close.cancel": "Cancel",
  "close.discard": "Discard changes",
} as const;

export type DesktopMessageKey = keyof typeof englishMessages;
type DesktopMessages = Record<DesktopMessageKey, string>;

const germanMessages: DesktopMessages = {
  "menu.settings": "Einstellungen…",
  "menu.file": "Datei",
  "menu.open": "Öffnen…",
  "menu.openProject": "Projekt öffnen…",
  "menu.closeDocument": "Datei schließen",
  "menu.closeProject": "Projekt schließen",
  "menu.save": "Speichern",
  "menu.saveAll": "Alles speichern",
  "menu.saveAs": "Speichern unter…",
  "menu.exportPng": "PNG exportieren…",
  "menu.edit": "Bearbeiten",
  "menu.undo": "Widerrufen",
  "menu.redo": "Wiederholen",
  "menu.cut": "Ausschneiden",
  "menu.copy": "Kopieren",
  "menu.paste": "Einsetzen",
  "menu.pasteMatch": "Einsetzen und Stil anpassen",
  "menu.delete": "Löschen",
  "menu.selectAll": "Alles auswählen",
  "menu.view": "Ansicht",
  "menu.reload": "Neu laden",
  "menu.forceReload": "Neu laden erzwingen",
  "menu.devTools": "Entwicklerwerkzeuge umschalten",
  "menu.resetZoom": "Originalgröße",
  "menu.zoomIn": "Vergrößern",
  "menu.zoomOut": "Verkleinern",
  "menu.fullscreen": "Vollbild umschalten",
  "menu.previewFocus": "Diagramm-Arbeitsfläche in voller Größe",
  "menu.previewWindow": "Diagrammfenster öffnen",
  "menu.window": "Fenster",
  "menu.minimize": "Minimieren",
  "menu.zoom": "Zoomen",
  "menu.front": "Alle nach vorne bringen",
  "menu.close": "Fenster schließen",
  "menu.about": "Über C4thedral",
  "menu.services": "Dienste",
  "menu.hide": "C4thedral ausblenden",
  "menu.hideOthers": "Andere ausblenden",
  "menu.showAll": "Alle einblenden",
  "menu.quit": "C4thedral beenden",
  "dialog.exportPng": "PNG-Diagramm exportieren",
  "dialog.exportSvg": "SVG-Diagramm exportieren",
  "dialog.open": "C4ML-Quelltext öffnen",
  "dialog.openProject": "C4ML-Projektverzeichnis öffnen",
  "dialog.save": "C4ML-Quelltext speichern",
  "filter.png": "PNG-Bild",
  "filter.svg": "SVG-Bild",
  "filter.c4ml": "C4ML-Quelltext",
  "filter.all": "Alle Dateien",
  "error.svgTooLarge": "Das SVG-Diagramm überschreitet das Desktop-Limit von 16 MiB.",
  "error.svgSave": "Das SVG-Diagramm konnte am gewählten Ort nicht gespeichert werden.",
  "error.pngRender": "Das aktuelle SVG-Diagramm konnte nicht als PNG gerendert werden.",
  "error.pngSave": "Das PNG-Diagramm konnte am gewählten Ort nicht gespeichert werden.",
  "error.sourceUnreadable": "Der ausgewählte Quelltext ist keine lesbare C4ML-Datei unter 8 MiB.",
  "error.projectUnreadable": "Mindestens eine Projektdatei überschreitet das Desktop-Limit von 8 MiB.",
  "error.sourceTooLarge": "Der C4ML-Quelltext überschreitet das Desktop-Limit von 8 MiB.",
  "error.sourceSave": "Der C4ML-Quelltext konnte am gewählten Ort nicht gespeichert werden.",
  "error.ipc": "Die Desktop-Anfrage wurde an der Anwendungsgrenze abgelehnt.",
  "error.sourceRead": "Der ausgewählte C4ML-Quelltext konnte nicht gelesen werden.",
  "close.title": "Ungespeicherter C4ML-Quelltext",
  "close.message": "Änderungen an {name} verwerfen?",
  "close.detail": "Der Quelltext enthält Änderungen, die noch nicht gespeichert wurden.",
  "close.cancel": "Abbrechen",
  "close.discard": "Änderungen verwerfen",
};

const messages: Record<DesktopUiLanguage, DesktopMessages> = {
  de: germanMessages,
  en: englishMessages,
};

export function desktopMessage(
  language: DesktopUiLanguage,
  key: DesktopMessageKey,
  parameters: Readonly<Record<string, string | number>> = {},
): string {
  let message: string = messages[language][key];
  for (const [name, value] of Object.entries(parameters)) {
    message = message.replaceAll(`{${name}}`, String(value));
  }
  return message;
}
