import type {
  ArchitectureModel,
  ArchitectureView,
  SourceReference,
} from "../src/index.js";

function source(line: number): SourceReference {
  return {
    file: "signal-garden.c4ml",
    range: {
      start: { line, column: 0, offset: line * 10 },
      end: { line, column: 9, offset: line * 10 + 9 },
    },
  };
}

export const signalGardenModel: ArchitectureModel = {
  elements: [
    {
      id: "grower",
      kind: "person",
      name: "Grower",
      description: "Plans and supervises cultivation cycles.",
      classification: "external",
      source: source(1),
    },
    {
      id: "signal-garden",
      kind: "software-system",
      name: "Signal Garden",
      description: "Coordinates cultivation plans from environmental signals.",
      classification: "internal",
      source: source(2),
    },
    {
      id: "weather-beacon",
      kind: "software-system",
      name: "Weather Beacon",
      description: "Publishes local weather observations.",
      classification: "external",
      source: source(3),
    },
    {
      id: "studio-ui",
      kind: "container",
      softwareSystemId: "signal-garden",
      name: "Cultivation Studio",
      description: "Presents plans and accepts cultivation changes.",
      technology: "TypeScript web application",
      source: source(4),
    },
    {
      id: "cultivation-api",
      kind: "container",
      softwareSystemId: "signal-garden",
      name: "Cultivation API",
      description: "Applies planning rules and coordinates observations.",
      technology: "TypeScript service",
      source: source(5),
    },
    {
      id: "ledger-store",
      kind: "container",
      softwareSystemId: "signal-garden",
      name: "Cultivation Ledger",
      description: "Stores plans, readings, and recommendations.",
      technology: "PostgreSQL",
      source: source(6),
    },
    {
      id: "notify-worker",
      kind: "container",
      softwareSystemId: "signal-garden",
      name: "Notification Worker",
      description: "Delivers time-sensitive cultivation notices.",
      technology: "TypeScript worker",
      source: source(7),
    },
    {
      id: "plan-controller",
      kind: "component",
      containerId: "cultivation-api",
      name: "Plan Controller",
      description: "Accepts and validates cultivation-plan requests.",
      technology: "HTTP controller",
      source: source(8),
    },
    {
      id: "recommendation-engine",
      kind: "component",
      containerId: "cultivation-api",
      name: "Recommendation Engine",
      description: "Calculates cultivation recommendations from observations.",
      technology: "Domain service",
      source: source(9),
    },
    {
      id: "zone-policy",
      kind: "code-element",
      componentId: "recommendation-engine",
      name: "Zone Policy",
      description: "Combines zone constraints into a recommendation.",
      codeKind: "module",
      language: "TypeScript",
      source: source(10),
    },
    {
      id: "moisture-index",
      kind: "code-element",
      componentId: "recommendation-engine",
      name: "Moisture Index",
      description: "Normalizes recent moisture observations.",
      codeKind: "function",
      language: "TypeScript",
      source: source(11),
    },
    {
      id: "request-mapper",
      kind: "code-element",
      componentId: "plan-controller",
      name: "Request Mapper",
      description: "Maps transport input to a cultivation plan command.",
      codeKind: "function",
      language: "TypeScript",
      source: source(12),
    },
  ],
  relationships: [
    {
      id: "grower-plans-system",
      sourceId: "grower",
      targetId: "signal-garden",
      description: "Plans and reviews cultivation cycles",
      source: source(20),
    },
    {
      id: "weather-feeds-system",
      sourceId: "weather-beacon",
      targetId: "signal-garden",
      description: "Provides local environmental observations",
      source: source(21),
    },
    {
      id: "grower-edits-ui",
      sourceId: "grower",
      targetId: "studio-ui",
      description: "Edits cultivation plans",
      source: source(22),
    },
    {
      id: "ui-calls-api",
      sourceId: "studio-ui",
      targetId: "cultivation-api",
      description: "Submits cultivation commands",
      technology: "HTTPS/JSON",
      source: source(23),
    },
    {
      id: "api-writes-ledger",
      sourceId: "cultivation-api",
      targetId: "ledger-store",
      description: "Stores plans and recommendations",
      protocol: "PostgreSQL wire protocol",
      source: source(24),
    },
    {
      id: "api-enqueues-notice",
      sourceId: "cultivation-api",
      targetId: "notify-worker",
      description: "Enqueues cultivation notices",
      protocol: "AMQP",
      source: source(25),
    },
    {
      id: "weather-feeds-api",
      sourceId: "weather-beacon",
      targetId: "cultivation-api",
      description: "Supplies current environmental observations",
      source: source(26),
    },
    {
      id: "weather-feeds-engine",
      sourceId: "weather-beacon",
      targetId: "recommendation-engine",
      description: "Supplies normalized observations",
      source: source(26),
    },
    {
      id: "ui-invokes-controller",
      sourceId: "studio-ui",
      targetId: "plan-controller",
      description: "Sends validated planning input",
      source: source(27),
    },
    {
      id: "controller-requests-recommendation",
      sourceId: "plan-controller",
      targetId: "recommendation-engine",
      description: "Requests a cultivation recommendation",
      source: source(28),
    },
    {
      id: "engine-reads-ledger",
      sourceId: "recommendation-engine",
      targetId: "ledger-store",
      description: "Reads recent cultivation observations",
      source: source(29),
    },
    {
      id: "grower-revises-plan",
      sourceId: "grower",
      targetId: "plan-controller",
      description: "Provides a revised cultivation plan",
      source: source(30),
    },
    {
      id: "policy-reads-index",
      sourceId: "zone-policy",
      targetId: "moisture-index",
      description: "Reads the normalized moisture score",
      source: source(31),
    },
  ],
  deployment: {
    environments: [
      {
        id: "production",
        kind: "deployment-environment",
        name: "Production",
        description: "The live cultivation service environment.",
        source: source(40),
      },
      {
        id: "staging",
        kind: "deployment-environment",
        name: "Staging",
        description: "The pre-release verification environment.",
        source: source(41),
      },
    ],
    nodes: [
      {
        id: "prod-cloud",
        kind: "deployment-node",
        environmentId: "production",
        name: "Production Cloud",
        description: "Hosts the live Signal Garden installation.",
        technology: "European cloud region",
        source: source(42),
      },
      {
        id: "prod-cluster",
        kind: "deployment-node",
        environmentId: "production",
        parentNodeId: "prod-cloud",
        name: "Application Cluster",
        description: "Runs user-facing and background services.",
        technology: "Kubernetes",
        source: source(43),
      },
      {
        id: "prod-data",
        kind: "deployment-node",
        environmentId: "production",
        parentNodeId: "prod-cloud",
        name: "Data Service",
        description: "Runs the managed cultivation ledger.",
        technology: "Managed PostgreSQL",
        source: source(44),
      },
      {
        id: "stage-host",
        kind: "deployment-node",
        environmentId: "staging",
        name: "Staging Host",
        description: "Runs the compact staging installation.",
        technology: "Virtual machine",
        source: source(45),
      },
    ],
    infrastructureNodes: [
      {
        id: "prod-gateway",
        kind: "infrastructure-node",
        environmentId: "production",
        nodeId: "prod-cloud",
        name: "Edge Gateway",
        description: "Terminates public HTTPS traffic.",
        technology: "Managed application gateway",
        source: source(46),
      },
    ],
    instances: [
      {
        id: "prod-system",
        kind: "software-system-instance",
        environmentId: "production",
        nodeId: "prod-cloud",
        softwareSystemId: "signal-garden",
        source: source(47),
      },
      {
        id: "prod-ui",
        kind: "container-instance",
        environmentId: "production",
        nodeId: "prod-cluster",
        containerId: "studio-ui",
        source: source(48),
      },
      {
        id: "prod-api",
        kind: "container-instance",
        environmentId: "production",
        nodeId: "prod-cluster",
        containerId: "cultivation-api",
        source: source(49),
      },
      {
        id: "prod-ledger",
        kind: "container-instance",
        environmentId: "production",
        nodeId: "prod-data",
        containerId: "ledger-store",
        source: source(50),
      },
      {
        id: "prod-worker",
        kind: "container-instance",
        environmentId: "production",
        nodeId: "prod-cluster",
        containerId: "notify-worker",
        source: source(51),
      },
      {
        id: "stage-api",
        kind: "container-instance",
        environmentId: "staging",
        nodeId: "stage-host",
        containerId: "cultivation-api",
        source: source(52),
      },
    ],
    relationships: [
      {
        id: "prod-gateway-ui",
        sourceId: "prod-gateway",
        targetId: "prod-ui",
        description: "Forwards browser requests",
        technology: "HTTPS",
        source: source(53),
      },
      {
        id: "prod-ui-api",
        sourceId: "prod-ui",
        targetId: "prod-api",
        description: "Submits cultivation commands",
        staticRelationshipId: "ui-calls-api",
        technology: "HTTPS/JSON",
        source: source(54),
      },
      {
        id: "prod-api-ledger",
        sourceId: "prod-api",
        targetId: "prod-ledger",
        description: "Stores plans and recommendations",
        staticRelationshipId: "api-writes-ledger",
        technology: "PostgreSQL wire protocol",
        source: source(55),
      },
      {
        id: "prod-api-worker",
        sourceId: "prod-api",
        targetId: "prod-worker",
        description: "Enqueues cultivation notices",
        staticRelationshipId: "api-enqueues-notice",
        technology: "AMQP",
        source: source(56),
      },
    ],
  },
};

export const signalGardenViews: readonly ArchitectureView[] = [
  {
    id: "portfolio",
    kind: "system-landscape",
    scope: "Cultivation Operations",
    title: "System Landscape — Cultivation Operations",
    purpose: "Shows the people and systems that exchange cultivation signals.",
  },
  {
    id: "signal-context",
    kind: "system-context",
    softwareSystemId: "signal-garden",
    title: "System Context — Signal Garden",
    purpose: "Explains who uses Signal Garden and which systems supply it.",
  },
  {
    id: "signal-containers",
    kind: "container",
    softwareSystemId: "signal-garden",
    title: "Container View — Signal Garden",
    purpose: "Explains the deployable responsibilities inside Signal Garden.",
  },
  {
    id: "api-components",
    kind: "component",
    containerId: "cultivation-api",
    title: "Component View — Cultivation API",
    purpose: "Explains how the API validates plans and calculates advice.",
  },
  {
    id: "engine-code",
    kind: "code",
    componentId: "recommendation-engine",
    title: "Code View — Recommendation Engine",
    purpose: "Explains the important policy and observation calculations.",
  },
  {
    id: "plan-cycle",
    kind: "dynamic",
    scenario: "Revise a cultivation plan",
    title: "Dynamic View — Revise a Cultivation Plan",
    purpose: "Explains the ordered collaboration for a plan revision.",
    display: "collaboration",
    interactions: [
      {
        id: "submit-plan",
        order: 1,
        sourceId: "studio-ui",
        targetId: "cultivation-api",
        description: "Submits the revised cultivation plan",
        relationshipId: "ui-calls-api",
        source: source(60),
      },
      {
        id: "store-plan",
        order: 2,
        parallelGroup: "persist-and-notify",
        sourceId: "cultivation-api",
        targetId: "ledger-store",
        description: "Stores the revised plan",
        relationshipId: "api-writes-ledger",
        source: source(61),
      },
      {
        id: "queue-notice",
        order: 2,
        parallelGroup: "persist-and-notify",
        sourceId: "cultivation-api",
        targetId: "notify-worker",
        description: "Queues a plan-change notice",
        relationshipId: "api-enqueues-notice",
        source: source(62),
      },
    ],
  },
  {
    id: "production-deployment",
    kind: "deployment",
    environmentId: "production",
    softwareSystemIds: ["signal-garden"],
    title: "Deployment View — Signal Garden Production",
    purpose: "Explains where the live Signal Garden services execute.",
  },
];
